### ISSUE TITLE
buy

### ISSUE THREAD

**Issue by nexetas** [berbb/PAIO-Issues#10]
nexete / Paid with

PayPal Balance 0,01 EUR
MasterCard x-8333 0,91 EUR
This transaction will appear on your statement as PAYPAL *PORTAIO
Purchase details

Receipt number: 0C3006179K889762K
We'll send confirmation to:
apalonke@gmail.com
Merchant details

PortAIO /Basic ($1) - 1 Month - Paypal & Bitcoin Only

**Comment by y0ste** [comment]
You got it all wrong, ohh man, go to your email and read the actual thing man.

**Comment by berbb** [comment]
added
