### ISSUE TITLE
winnermulti3 - 6990f34c-257f-4cc0-9dc2-d1ab6789e9fc - Advanced

### ISSUE THREAD

**Issue by winnershark** [berbb/PAIO-Issues#42]
Elobuddy ID:  winnermulti3

invoice ID
6990f34c-257f-4cc0-9dc2-d1ab6789e9fc

구매 세부정보
Order 6990f34c-257f-4cc0-9dc2-d1ab6789e9fc

**Comment by berbb** [comment]
added
